/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Local_Censor */

#ifndef _Included_Local_Censor
#define _Included_Local_Censor
#ifdef __cplusplus
extern "C" {
#endif
#undef Local_Censor_MIN_PRIORITY
#define Local_Censor_MIN_PRIORITY 1L
#undef Local_Censor_NORM_PRIORITY
#define Local_Censor_NORM_PRIORITY 5L
#undef Local_Censor_MAX_PRIORITY
#define Local_Censor_MAX_PRIORITY 10L
/*
 * Class:     Local_Censor
 * Method:    inputTemperatura
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Local_00024Censor_inputTemperatura
  (JNIEnv *, jobject);

/*
 * Class:     Local_Censor
 * Method:    inputHumedad
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Local_00024Censor_inputHumedad
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
